import _isDayOfMonth from './common/isDayOfMonth/isDayOfMonth';
import _isDayOfWeekString from './common/isDayOfWeekString/isDayOfWeekString';
import _isEmail from './common/isEmail/isEmail';
import _isHexValue from './common/isHexValue/isHexValue';
import _isHTMLTag from './common/isHTMLTag/isHTMLTag';
import _isInteger from './common/isInteger/isInteger';
import _isIPAddressV4 from './common/isIPAddressV4/isIPAddressV4';
import _isLetter from './common/isLetter/isLetter';
import _isLowerCase from './common/isLowerCase/isLowerCase';
import _isMonthOfYear from './common/isMonthOfYear/isMonthOfYear';
import _isMonthOfYearString from './common/isMonthOfYearString/isMonthOfYearString';
import _isNegativeInteger from './common/isNegativeInteger/isNegativeInteger';
import _isNegativeNumber from './common/isNegativeNumber/isNegativeNumber';
import _isNumber from './common/isNumber/isNumber';
import _isPassword from './common/isPassword/isPassword';
import _isPositiveInteger from './common/isPositiveInteger/isPositiveInteger';
import _isPositiveNumber from './common/isPositiveNumber/isPositiveNumber';
import _isSSN from './common/isSSN/isSSN';
import _isUpperCase from './common/isUpperCase/isUpperCase';
import _isUrl from './common/isUrl/isUrl';
import _isUsername from './common/isUsername/isUsername';
import _isUSPhoneNumber from './common/isUSPhoneNumber/isUSPhoneNumber';
import _isVowel from './common/isVowel/isVowel';
import _isYear from './common/isYear/isYear';

export const isDayOfMonth = _isDayOfMonth;
export const isDayOfWeekString = _isDayOfWeekString;
export const isEmail = _isEmail;
export const isHexValue = _isHexValue;
export const isHTMLTag = _isHTMLTag;
export const isInteger = _isInteger;
export const isIPAddressV4 = _isIPAddressV4;
export const isLetter = _isLetter;
export const isLowerCase = _isLowerCase;
export const isMonthOfYear = _isMonthOfYear;
export const isMonthOfYearString = _isMonthOfYearString;
export const isNegativeInteger = _isNegativeInteger;
export const isNegativeNumber = _isNegativeNumber;
export const isNumber = _isNumber;
export const isPassword = _isPassword;
export const isPositiveInteger = _isPositiveInteger;
export const isPositiveNumber = _isPositiveNumber;
export const isSSN = _isSSN;
export const isUpperCase = _isUpperCase;
export const isUrl = _isUrl;
export const isUsername = _isUsername;
export const isUSPhoneNumber = _isUSPhoneNumber;
export const isVowel = _isVowel;
export const isYear = _isYear;

